version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=platform
      - POSTGRES_DB=platform
    ports:
      - '5432:5432'
    networks:
      - platform
networks:
  platform: null